version: 2.1
orbs:
    # sfdx: circleci/salesforce-sfdx@2.2.0
    salesforce: jsc/salesforce@2.1.0

jobs:
  validate:
    executor: salesforce/default
    steps:
      - checkout
      - salesforce/install:
          version: "latest"
      - run:
          name: Login to Sandbox
          command: . build/auth.sh
      - run:
          name: Validate to Sandbox
          no_output_timeout: 60m
          command: . build/validate.sh
  validate-ci:
    executor: salesforce/default
    steps:
      - checkout
      - salesforce/install:
          version: "latest"
      - run:
          name: Login & Validate to Sandbox
          no_output_timeout: 90m
          command: . build/auth_validate.sh
  deploy:
    executor: salesforce/default
    steps:
      - checkout
      - salesforce/install:
          version: "latest"
      - run:
          name: Login to Sandbox
          command: . build/auth.sh
      - run:
          name: Deploy to Sandbox
          no_output_timeout: 60m
          command: . build/deploy.sh
workflows:
  validate:
    jobs:
      - validate-ci:
          context: RLM SF CI
  deploy-qa:
    jobs:
      - deploy:
          context: RLM SF QA
          filters:
            branches:
              only:
                - integration/qa
  deploy-uat:
    jobs:
      - deploy:
          context: RLM SF UAT
          filters:
            branches:
              only:
                - integration/uat
  deploy-preprod:
    jobs:
      - hold:
          type: approval
          filters:
            branches:
              only:
                - main
      - deploy:
          context: RLM SF PREPROD
          requires:
            - hold
  deploy-prod:
    jobs:
      - validate:
          context: RLM SF PROD
          filters:
            tags:
              only:
                - /(v[0-9]*\.[0-9])/
            branches:
              ignore: /.*/
      - hold:
          type: approval
          requires:
            - validate
          filters:
            tags:
              only:
                - /(v[0-9]*\.[0-9])/
            branches:
              ignore: /.*/
      - deploy:
          context: RLM SF PROD
          requires:
            - hold
          filters:
            tags:
              only:
                - /(v[0-9]*\.[0-9])/
            branches:
              ignore: /.*/
      - deploy:
          context: RLM SF QA
          requires:
            - hold
          filters:
            tags:
              only:
                - /(v[0-9]*\.[0-9])/
            branches:
              ignore: /.*/
      - deploy:
          context: RLM SF DATAMIG
          requires:
            - hold
          filters:
            tags:
              only:
                - /(v[0-9]*\.[0-9])/
            branches:
              ignore: /.*/
